imports:
    - php
checks:
    php:
        code_rating: true
        duplication: true
        excluded_dependencies:
            - hiqdev/composer-config-plugin
            - phpunit/phpunit
            - fzaninotto/faker

tools:
    external_code_coverage: true
    external_code_coverage:
        timeout: 2100
    php_sim: false
    php_cpd: false
filter:
    excluded_paths:
        - config/*
        - docs/*
        - tests/*
        - vendor/*
